### PR TITLE
BUGFIX: Load Subjects (from PR #29)

### LINKED ISSUE #33: Update Subjects frontend with SubjectsTable instead of the placeholder LoadSubjects
This issue addressed the differences in code between #14 and the code in #11 and #12.
Currently, #11 and #12 are using a placeholder table that doesn't include the edit and delete functions.

- [x] Subject pages are using SubjectsTable instead of placeholders
- [x] JS tests are using SubjectsTable elements instead of LoadSubjectTable element

### LINKED ISSUE #36: Bug: Load Subjects (from PR #29) doesn't work
BUG: The load subjects button added in PR #29 doesn't work.

Steps to Reproduce:

1. Log in as admin
2. Use swagger back end endpoint to delete all subjects
3. Go to Load Subjects page
4. Click Load Subjects

Expected:

Subjects are loaded into database, and a toast appears with the number of subjects loaded.

Observed:

A 500 error

# Screenshot

image

### PR DESCRIPTION
**Pull request by edisonnchen**
# Overview

In this PR, we fix the backend bug of Load Subjects. Subjects should be loaded in properly. Toastify now remembers number of subjects loaded even when full page is reloaded. Toastify also returns the proper amount of subjects returned based on the difference between subjects on table and new subjects loaded.

# Issues Addressed

Closes #33 #36

# Details

The bug was caused by the API key not being available. It seemed to have been fixed when the branch merged to main. I modified the Load Subject Page and its tests to use UCSBSubjects instead of the placeholder LoadSubjects.

### CODE REVIEW

**Review by bobhe9606 — DISMISSED** [review]
LGTM

File: frontend/src/main/pages/LoadSubjectsPage.js [hunk 1]
```diff
@@ -26,14 +26,21 @@ const LoadSubjectsPage = () => {
...
+  subjectsCount = subjects.length;
+
   const onSuccess = (subjects) => {
-    if (subjectsCount === subjects.length) {
+    if (subjects.length - subjectsCount === 0) {
       toast('No new subjects were loaded');
     } else {
-      toast(`${subjects.length} subjects loaded`);
-      subjectsCount = subjects.length;
+      if (subjects.length - subjectsCount === 1) {
```
Comment (Wenjin09) [inline frontend/src/main/pages/LoadSubjectsPage.js:35]: idk if this will cause errors or not show properly if "subjects.length - subjectsCount" is more than 1

**Review by Wenjin09 — APPROVED** [review]
LGTM, working fine when deploy the branch: 7pm-2-ec-subjectsLoad
image

# screenshot for both links
team04-w22-7pm-2:
image

team04-w22-7pm-2-qa:
image

File: frontend/src/main/pages/LoadSubjectsPage.js (hunk 1 above)
Comment (andrewhlu) [reply frontend/src/main/pages/LoadSubjectsPage.js:35]: This looks correct - this `if` statement is to handle the case where `subject` has to be singular in the toast message per grammar rules.

**Review by pconrad — APPROVED** [review]
Code LGTM---will merge if testing on Heroku checks out.
